name: Bug report
description: Report a reproducible bug in LOOM protocol/node behavior.
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please include enough detail to reproduce.
  - type: input
    id: version
    attributes:
      label: Version / commit
      description: Tag, branch, or commit SHA where this occurs.
      placeholder: "v0.2.6 or main@<sha>"
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - protocol
        - api
        - federation
        - wire-gateway
        - persistence
        - docs
        - other
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Provide a minimal sequence that reproduces the issue.
      placeholder: |
        1. Start server with ...
        2. Send request ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / payloads (sanitized)
      description: Remove secrets before posting.
